language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - pypy

env:
  - BUILD_CAPNP=true
  - BUILD_CAPNP=

compiler: gcc

before_install:
  - buildutils/setup_travis.sh
  - pip install -U setuptools
  - pip install cython
  - pip install pytest

install:
  - pip install --editable .

script: py.test test
