language: python

python:
  - 2.7
compiler: clang

before_install:
  - "curl -L https://gist.github.com/jparyani/6216515/raw/a50cb02574033a14f3856dac949f83b4c0557c82/install_capnproto.sh | /bin/bash"

install:
  - pip install --editable .

matrix:
  allow_failures:
    - python: pypy

script: true
