language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy

compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8 libstdc++-4.8-dev
  - sudo update-alternatives --quiet --install /usr/bin/gcc  gcc  /usr/bin/gcc-4.8  60
                                     --slave   /usr/bin/g++  g++  /usr/bin/g++-4.8
                                     --slave   /usr/bin/gcov gcov /usr/bin/gcov-4.8
  - sudo update-alternatives --quiet --set gcc /usr/bin/gcc-4.8
  - "https://gist.github.com/jparyani/6216515/raw/bd1d53a598e104489179d1a345b1ebf7bc1cdc73/install_capnproto.sh | /bin/bash"
  - pip install -U setuptools
  - pip install cython

install:
  - pip install --editable .

script: cd examples && python example.py
